overrides:
  '@speed-highlight/core': 1.2.16
  esbuild: 0.28.1

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - workerd

allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true
